### ISSUE TITLE
[Linux] CMake does not find the static library when trying to import

### ISSUE THREAD

**Issue by srupprecht-tt** [aas-core-works/aas-core3.0-cpp#22]
Hey there,

I am using Ubuntu 20.04.6 LTS. There are no errors when running `make install`, but when trying to build my own project which uses `find_package(aas_core3 0 REQUIRED)` inside the CMake file, I get the following error:
```CMake
[cmake] CMake Error at /usr/local/lib/cmake/aas_core3/aas_core3.cmake:93 (message):
[cmake]   The imported target "aas_core3_static" references the file
[cmake] 
[cmake]      "/lib/libaas_core3_static.a"
[cmake] 
[cmake]   but this file does not exist.  Possible reasons include:
[cmake] 
[cmake]   * The file was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and contained
[cmake] 
[cmake]      "/usr/local/lib/cmake/aas_core3/aas_core3.cmake"
[cmake] 
[cmake]   but not all the files it references.
[cmake] Call Stack (most recent call first):
[cmake]   /usr/local/lib/cmake/aas_core3/aas_core3-config.cmake:6 (include)
[cmake]   /home/srupprecht/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
[cmake]   CMakeLists.txt:14 (find_package)
```

My current solution is to redefine the CMAKE_INSTALL_PREFIX as well as CMAKE_INSTALL_LIBDIR s.t. the files do not get installed into `/usr/local/`:
```CMake
if (UNIX)
    if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
        set(CMAKE_INSTALL_PREFIX "/usr" CACHE PATH "..." FORCE)
    endif ()
endif ()
if (UNIX)
    set(CMAKE_INSTALL_LIBDIR "/lib")
endif ()
```

Adding this somewhere into the CMake file of aas-core-works (before the `install`-commands) should solve the problem. I don't know if there is a easier solution to this.

**Comment by mristin** [comment]
Hi @srupprecht-tt ,
I had another look. It seems to me that there is an error on your side -- did you set your desired `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` accordingly, say, with `--prefix` or `-DCMAKE_INSTALL_LIBDIR` and `-DCMAKE_INSTALL_INCLUDEDIR`?

Here is the relevant snippet from the current CMakeLists.txt:
https://github.com/aas-core-works/aas-core3.0-cpp/blob/aa0f76cb3ea8e9fdc08c2dd93f6941fd0b44a1b6/CMakeLists.txt#L331-L351

**Comment by srupprecht-tt** [comment]
Hi @mristin,
after setting the CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_PREFIX to the values mentioned above, everything worked fine.
I was just pointing out that my cmake-gui did *per default* use the wrong destination path for the installation folders. So maybe there is a wrong default configuration for the cmake-gui on my side. :)
Also wanted to point this error out in case someone runs into the same trouble.

**Comment by mristin** [comment]
Thanks for the info, @srupprecht-tt ! If I understand you correctly, the issue can be closed? Please re-open if there are further problems.
