### ISSUE TITLE
Error while building library optional-1.1.0

### ISSUE THREAD

**Issue by hbo-thorsis** [aas-core-works/aas-core3.0-cpp#6]
an error occours while building optional-1.1.0  (see attache logfile)

Compiler:  gcc and clang

Workaround: Change file "optional-1.1.0/build/_deps/catch2-src/single_include/catch2/catch.hpp" at line 10.453

old:  `static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;`
new: `static constexpr std::size_t sigStackSize = 32768;// >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;`

this way compiling worked.

[log.txt](https://github.com/aas-core-works/aas-core3.0-cpp/files/14040859/log.txt)

**Comment by mristin** [comment]
Thanks for the report, @hbo-thorsis !

I suppose you mean the dependency `tl/optional`? Can you please give me more information -- how did you install it (using vcpkg? conan?), and could you compile it independently of the aas-core-cpp?

**Comment by mristin** [comment]
P.S. Catch2 is a library used for testing -- and if it comes from `tl/optional`, it shouldn't be actually required when you build it. Have you already contacted `tl/optional` developers?

**Comment by hbo-thorsis** [comment]
Thanks for the reply, @mristin 

I have installed tl/optional manually. When using vcpkg everything works fine. 

Hagen.

**Comment by mristin** [comment]
Ok, I'll close the issue for now. Please re-open if there are more problems.
